<?php

/**
 * @file
 * Install, update, and uninstall functions for the gherkin module.
 */

/**
 * Implements hook_install().
 */
function gherkin_install() {
  $install_message = t("Automated tests using Gherkin, Run tests, and create tests under Administration -> Configuration -> Development -> Gherkin");
  \Drupal::logger('gherkin')->notice($install_message);
  \Drupal::messenger()->addWarning($install_message);
}
