field.field_settings.gherkin_default_widget:
  type: mapping
  label: 'Gherkin Script settings'
  mapping:
    size:
      type: integer
      label: 'Size'
    theme:  
      type: string
      label: 'Gherkin Theme'